In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
ausol_data = pd.read_csv('C:\\Users\\yhoz\\Documents\\dataanalytics.predictive\\data\\ausol\\datasets\\anual_data_2018.csv', delimiter=";")

In [4]:
ausol_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390512 entries, 0 to 1390511
Data columns (total 32 columns):
ID_SEGMENT            1390512 non-null int64
COD_LABORALIDAD       1390512 non-null int64
FECHA                 1390512 non-null object
MES                   1390512 non-null int64
HORA                  1390512 non-null int64
MINUTO                1390512 non-null int64
CANTIDAD_PREC         1390512 non-null int64
TOTAL_VEHICULOS       1004224 non-null float64
TOTAL_VEHICULOS_1     1021224 non-null float64
TOTAL_VEHICULOS_2     1025172 non-null float64
TOTAL_VEHICULOS_3     1027904 non-null float64
TOTAL_VEHICULOS_4     1030663 non-null float64
TOTAL_VEHICULOS_5     1032772 non-null float64
TOTAL_VEHICULOS_6     1034784 non-null float64
TOTAL_VEHICULOS_7     1036365 non-null float64
TOTAL_VEHICULOS_8     1037742 non-null float64
TOTAL_VEHICULOS_9     1038920 non-null float64
TOTAL_VEHICULOS_10    1040093 non-null float64
TOTAL_VEHICULOS_11    1041210 non-null float64
TOTAL_V

In [5]:
ausol_data.ID_SEGMENT.unique()

array([  1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  30,  31,  32,  33,  34,
        35,  39,  40,  42,  43, 100, 101, 102, 103, 104, 105, 106, 107],
      dtype=int64)

In [9]:
ausol_data['FECHA'] = pd.to_datetime(ausol_data['FECHA'])
ausol_data.FECHA.dt.year.unique()

array([2018], dtype=int64)

In [10]:
ausol_data.COD_LABORALIDAD.unique()

array([4, 3, 1, 2, 6, 5], dtype=int64)

In [11]:
# Codigos de laboralidad por mes
for month_i in range(1,13):
    ausol_data_month = ausol_data.loc[ausol_data.MES==month_i]
    print(ausol_data_month.COD_LABORALIDAD.unique())

[4 3 1 2]
[1 3 2]
[1 3 2 6 4 5]
[4 1 2 3 6 5]
[4 1 2 3]
[2 1 3]
[3 1 2]
[1 3 6 4 5 2]
[3 1 2]
[1 4 2 3 6 5]
[4 3 5 1 2]
[3 4 1 5 6 2]


In [12]:
ausol_data.TOTAL_VEHICULOS.isnull().sum() # sum() to count them

386288

In [13]:
ausol_data.TOTAL_VEHICULOS.fillna(method='ffill', inplace=True)

In [14]:
# Missing values por mes
for month_i in range(1,13):
    ausol_data_month = ausol_data.loc[ausol_data.MES==month_i]
    print("Month: " + str(month_i))
    print("MISSING "+ str(ausol_data_month.TOTAL_VEHICULOS.isnull().sum()))
    print("TOTAL "+ str(ausol_data_month.TOTAL_VEHICULOS.sum()))

Month: 1
MISSING 0
TOTAL 17087252.0
Month: 2
MISSING 0
TOTAL 16500496.0
Month: 3
MISSING 0
TOTAL 25128235.0
Month: 4
MISSING 0
TOTAL 26968599.0
Month: 5
MISSING 0
TOTAL 28608439.0
Month: 6
MISSING 0
TOTAL 26943226.0
Month: 7
MISSING 0
TOTAL 32495549.0
Month: 8
MISSING 0
TOTAL 33798874.0
Month: 9
MISSING 0
TOTAL 27136073.0
Month: 10
MISSING 0
TOTAL 23184407.0
Month: 11
MISSING 0
TOTAL 21520313.0
Month: 12
MISSING 0
TOTAL 18844985.0


In [15]:
ausol_data.isnull().sum() # sum() to count them

ID_SEGMENT                 0
COD_LABORALIDAD            0
FECHA                      0
MES                        0
HORA                       0
MINUTO                     0
CANTIDAD_PREC              0
TOTAL_VEHICULOS            0
TOTAL_VEHICULOS_1     369288
TOTAL_VEHICULOS_2     365340
TOTAL_VEHICULOS_3     362608
TOTAL_VEHICULOS_4     359849
TOTAL_VEHICULOS_5     357740
TOTAL_VEHICULOS_6     355728
TOTAL_VEHICULOS_7     354147
TOTAL_VEHICULOS_8     352770
TOTAL_VEHICULOS_9     351592
TOTAL_VEHICULOS_10    350419
TOTAL_VEHICULOS_11    349302
TOTAL_VEHICULOS_12    348326
TOTAL_VEHICULOS_13    347433
TOTAL_VEHICULOS_14    346463
TOTAL_VEHICULOS_15    345654
TOTAL_VEHICULOS_16    344724
TOTAL_VEHICULOS_17    343554
TOTAL_VEHICULOS_18    342378
TOTAL_VEHICULOS_19    340960
TOTAL_VEHICULOS_20    337800
TOTAL_VEHICULOS_21    336181
TOTAL_VEHICULOS_22    333352
TOTAL_VEHICULOS_23    329416
TOTAL_VEHICULOS_24    325821
dtype: int64

In [16]:
ausol_data = ausol_data.drop_duplicates(['MES','FECHA', 'ID_SEGMENT'], keep='first')

In [17]:
ausol_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1366560 entries, 0 to 1390511
Data columns (total 32 columns):
ID_SEGMENT            1366560 non-null int64
COD_LABORALIDAD       1366560 non-null int64
FECHA                 1366560 non-null datetime64[ns]
MES                   1366560 non-null int64
HORA                  1366560 non-null int64
MINUTO                1366560 non-null int64
CANTIDAD_PREC         1366560 non-null int64
TOTAL_VEHICULOS       1366560 non-null float64
TOTAL_VEHICULOS_1     997295 non-null float64
TOTAL_VEHICULOS_2     1001220 non-null float64
TOTAL_VEHICULOS_3     1003952 non-null float64
TOTAL_VEHICULOS_4     1006711 non-null float64
TOTAL_VEHICULOS_5     1008820 non-null float64
TOTAL_VEHICULOS_6     1010832 non-null float64
TOTAL_VEHICULOS_7     1012413 non-null float64
TOTAL_VEHICULOS_8     1013790 non-null float64
TOTAL_VEHICULOS_9     1014968 non-null float64
TOTAL_VEHICULOS_10    1016141 non-null float64
TOTAL_VEHICULOS_11    1017258 non-null float64


In [18]:
ausol_data.to_csv("C:\\Users\\yhoz\\Documents\\dataanalytics.predictive\\data\\ausol\\datasets\\cleaned\\anual_data_2018_mod.csv", sep=';', index=False)

In [19]:
ausol_data_mod = pd.read_csv('C:\\Users\\yhoz\\Documents\\dataanalytics.predictive\\data\\ausol\\datasets\\cleaned\\anual_data_2018_mod.csv', delimiter=";")

In [24]:
# save by month
for month_i in range(1,13):
    ausol_data_month = ausol_data_mod.loc[ausol_data_mod.MES==month_i]
    ausol_data_month.to_csv("C:\\Users\\yhoz\\Documents\\dataanalytics.predictive\\data\\ausol\\datasets\\cleaned\\" + "{:02d}".format(month_i) + "-18.csv", sep=';', index=False)